### ISSUE TITLE
elasticsearch docker-compose up error 

### ISSUE THREAD

**Issue by amorZhu** [elastic/elasticsearch-docker#153]
[2018-03-27T04:02:29,537][INFO ][o.e.n.Node               ] [] initializing ...
es_pc_soft            | [2018-03-27T04:02:29,551][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
es_pc_soft            | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
es_pc_soft            | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | Caused by: java.lang.IllegalStateException: Failed to create node environment
es_pc_soft            | 	at org.elasticsearch.node.Node.<init>(Node.java:267) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	... 6 more
es_pc_soft            | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
es_pc_soft            | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
es_pc_soft            | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
es_pc_soft            | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
es_pc_soft            | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
es_pc_soft            | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_161]
es_pc_soft            | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_161]
es_pc_soft            | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_161]
es_pc_soft            | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.node.Node.<init>(Node.java:264) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.3.jar:6.2.3]
es_pc_soft            | 	... 6 more

**Comment by jarpy** [comment]
> Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes

Please take a look this section of the documentation, which covers file permissions for the data directory:

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docker.html#_notes_for_production_use_and_defaults

In short, the directory in question must be writable by UID 1000, which is the UID running the Elasticsearch process.
