### ISSUE TITLE
When I try to install elasticsearch ,I get in trouble.What should I do?

### ISSUE THREAD

**Issue by yangjingying1993** [elastic/elasticsearch-docker#156]
yjy@ddh:/opt/elasticsearch-6.2.3/bin$ ./elasticsearch
Exception in thread "main" java.nio.file.AccessDeniedException: /opt/elasticsearch-6.2.3/config/jvm.options
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:58)

**Comment by xeraa** [comment]
Please follow the template that is preloaded when you open the issue — it makes it much easier for us to help you :)

Are you even using our Docker containers, because I cannot see anything around that in your problem? Generally this looks more like a question for https://discuss.elastic.co. Please start a discussion there and add more information: What system are you using, which package did you install,..
