### ISSUE TITLE
Elasicsearch fail to start with custom Dockerfile

### ISSUE THREAD

**Issue by mattiasnixell** [elastic/elasticsearch-docker#227]
My goal is to build a custom Docker image from `elasticsearch:5.3.2` and create an index as part of the image. I got the scripts figured out (thanks to stackoverflow <3) and it works just fine. However, I have to group most commands that I run inside the image (Dockerfile), otherwise the elasticsearch service fails with the error `failed to obtain node locks` (more details below). I don't understand the correlation between the amount of build steps and the obtaining of node locks.

## Environment

* Docker image used `docker.elastic.co/elasticsearch/elasticsearch:5.3.2`
* Operating System
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.10586 N/A Build 10586
```
* `docker info` output
```
Containers: 110
 Running: 24
 Paused: 0
 Stopped: 86
Images: 408
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.844GiB
Name: moby
ID: X5UC:3GJX:VEP5:LT42:5BLY:HA3M:ESA3:5QX4:CC6I:NGN3:OCY3:JKIM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 181
 Goroutines: 288
 System Time: 2018-12-28T13:40:49.4291606Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* `docker inspect NAME|ID` output
```
[
    {
        "Id": "sha256:6cb0ae81e0756a16fc98ed5facb7dd8670cd6e2ee5853f305928492fea0402b7",
        "RepoTags": [],
        "RepoDigests": [],
        "Parent": "sha256:12ef4f884c73935e4ddecd8cbed1e48edfa5183d9749ab58f1962e54758a6318",
        "Comment": "",
        "Created": "2018-12-28T13:45:44.8511045Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "84baa8e89c00",
            "Domainname": "",
            "User": "elasticsearch",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9200/tcp": {},
                "9300/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) COPY dir:921a5dcf402f9e975f4834dacbce0c57451c802b74667ae32538c738e1995781 in /elasticsearch/ "
            ],
            "ArgsEscaped": true,
            "Image": "sha256:12ef4f884c73935e4ddecd8cbed1e48edfa5183d9749ab58f1962e54758a6318",
            "Volumes": null,
            "WorkingDir": "/usr/share/elasticsearch",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "84baa8e89c00",
            "Domainname": "",
            "User": "elasticsearch",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9200/tcp": {},
                "9300/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk"
            ],
            "Cmd": [
                "/bin/bash",
                "bin/es-docker"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:12ef4f884c73935e4ddecd8cbed1e48edfa5183d9749ab58f1962e54758a6318",
            "Volumes": null,
            "WorkingDir": "/usr/share/elasticsearch",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 163944736,
        "VirtualSize": 163944736,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/acb58749fd9ae3e6eef2bb15c09835ae521c2328089bb511a7477152b33561d7/diff:/var/lib/docker/overlay2/4a395b513fdc7af7d9a124525ab00da8ca92ddbc796a0b6d60eb8218b89a21c4/diff:/var/lib/docker/overlay2/c8c71d298cfe70f197af953d
6b885d133b24761e570c97e5bb3693a84fcfaf89/diff:/var/lib/docker/overlay2/04b3833b20920d82ca6c15439a430218c8a10cbfabfa58a6c3aa6e93e143b224/diff:/var/lib/docker/overlay2/17cb0a81daff5219c4f88dace78736088139e01cfebb8ff1ea50ae803d3705d0/diff:/var/lib/docker/overlay2/c06e687
368e727219abcf1eeb5ab3604c37714063994b8a765f1de99ab9f0a55/diff:/var/lib/docker/overlay2/fa0e0e6b67664639c8a61bc5ffd02eb6486be7c47dd52bc64b1ad155fdbfcff5/diff:/var/lib/docker/overlay2/99ab05ed585b66c3c878ec4e0c4766f4d465b1e9d474c64bdf7ced4271eacb2d/diff:/var/lib/docker
/overlay2/bd84c514811cad9fd377c91c457675630a1dd20865dba1be09c83a65775fcb49/diff:/var/lib/docker/overlay2/e7efc4e016f206cc102f58d84dc39f90ccbd8e0df38a12a056aebb30c91f9bd2/diff:/var/lib/docker/overlay2/44a8fa201811a316b661872f470c13cf8075c31a7380e3bc21d15eb3da8a4769/dif
f:/var/lib/docker/overlay2/d76c62fb926c55773115a878d12a8a7709dd78053d44a8a0c9b36aee965cf809/diff:/var/lib/docker/overlay2/83a88fabfa5a29ec9d6e1f7764b81ebd18d8fff4eee19f05bcf6ff8fbb475818/diff:/var/lib/docker/overlay2/a3a5cbbe2beb5bfd66c1be0277398ebb6d5edb0304f8b5c9f10
14992a251487d/diff",
                "MergedDir": "/var/lib/docker/overlay2/f0cc16e4e38687bac86c279e2ad997287674c04268b6b78b8ba891b9b5fc530a/merged",
                "UpperDir": "/var/lib/docker/overlay2/f0cc16e4e38687bac86c279e2ad997287674c04268b6b78b8ba891b9b5fc530a/diff",
                "WorkDir": "/var/lib/docker/overlay2/f0cc16e4e38687bac86c279e2ad997287674c04268b6b78b8ba891b9b5fc530a/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:23b9c7b43573dd164619ad59e9d51eda4095926729f59d5f22803bcbe9ab24c2",
                "sha256:e064fe42c0bc59cb55157f4e4ca5ed8760ce58a63e45019158fe1d1b5385c434",
                "sha256:6ada81d82f0af3ae7a357af48cb2bac36a0ff02eebeb7cbd9ddd8246e4440d2b",
                "sha256:48a1c138e09468427d363e5b43378f8aa8d3d469bab0d351f5b2b99ae96f53d4",
                "sha256:cd3f8706fe62384b144810a97c0415909422c14bb34da3a78cdf5e03df7aae75",
                "sha256:b8361cb05f4eb475078f9b16c650a2cd0063ca72fe6322b622dc9f86eabc8b72",
                "sha256:caa91c6f1d1ea0eb70fe1de62f02dc8d3cdbbc41deddd1d5b28df5972a73d664",
                "sha256:2aba3e54f9a5b5c1368af156ab86df87b9114ea150aff2477d0c61b4b855935e",
                "sha256:6e13c07336d9f0db49c051c92485416277feaeecab9dc204cc2fee41c0b2d3c2",
                "sha256:e682c651ef76896557f00b88e619f5b8e3c08a3994339c3d92c73b22bdccffbd",
                "sha256:5b3305fd569d8f13f59c5af09ebb0d161f7b4e8436458b02ac94058b95acb33f",
                "sha256:3ed3d986c69681a3a01f62be00459723117e46fecebb7a6ba22d11abda867b41",
                "sha256:7031666ba5094a508debb86dddb6cc8c33521c17cf67b03fc1c0ff71fea1f989",
                "sha256:5ea406fc882ea675d9de7d811982c898026bf1a83a8b7a3e6f45bae2cb575251",
                "sha256:d28b5f8a268af37af797b68d0b68f127a6f98ef20a26f7413db55ddfcaab4afd"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
* `docker-compose version 1.16.1, build 6d1ac219`
* Steps to reproduce
  * Create a custom Dockerfile from `elasticsearch:5.3.2` with at least 8 steps (running elasticsearch service as the last one).
  * Build the Dockerfile (same result with both `docker build ./` and `docker-compose build`)
  * Fails when initializing with error:
```
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.2.jar:5.3.2]n]
org.elasat org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.2.jar:5.3.2]data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storag
e_nodes]at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.2.jar:5.3.2]arch-5.3.2.jar:5.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.2.jar:5.3.2]
Caused bat org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:260) ~[elasticsearch-5.3.2.jar:5.3.2]id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2].2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:239) ~[elasticsearch-5.3.2.jar:5.3.2]
Caused bat org.elasticsearch.node.Node.<init>(Node.java:262) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]]
        ... 6 moresticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
Caused bat sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91) ~[?:?]
        at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44) ~[?:?]
        at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39) ~[?:?]
        at java.nio.file.Files.getFileStore(Files.java:1461) ~[?:1.8.0_121]vider.java:368) ~[?:?]
        at org.elasticsearch.env.Environment.getFileStore(Environment.java:351) ~[elasticsearch-5.3.2.jar:5.3.2]r:5.3.2]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:227) ~[elasticsearch-5.3.2.jar:5.3.2]ar:5.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2].2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
        ... 6 more
```

## Bug Description

A custom Dockerfile build fails when trying to run the elasticsearch service as part of the build process when including 8 or more steps. I have investigated if there was any kind of permission issues inside the image, which seemed to have been the problem for some when they got the above error message. According to my understanding, everything is in place. I even tried to set full permissions on all relevant folders, but without success.

I also noticed that a Dockerfile build succeeds with 8 or more steps without elasticsearch service running as part of the build process. However, when starting a container with the image it fails with the same error as described above.

To have both a successful Dockerfile build and docker run, one can include a maximum of 6 steps.

### Example of **Failing** Dockerfile

```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.2

USER root

RUN mkdir /data
RUN chown -R elasticsearch:elasticsearch /data
RUN echo 'path.data: /data' >> config/elasticsearch.yml
RUN echo 'xpack.security.enabled: false' >> config/elasticsearch.yml

USER elasticsearch

COPY ./elasticsearch /elasticsearch/

RUN /bin/bash bin/elasticsearch -p /tmp/epid & \
  /bin/bash /elasticsearch/scripts/wait-for-it.sh -t 0 localhost:9200 -- /elasticsearch/scripts/build-index.sh; kill $(cat /tmp/epid) && \
  wait $(cat /tmp/epid); exit 0;
```
### Example of **Successful** Dockerfile

```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.2

USER root

RUN mkdir /data && \
  chown -R elasticsearch:elasticsearch /data && \
  echo 'path.data: /data' >> config/elasticsearch.yml && \
  echo 'xpack.security.enabled: false' >> config/elasticsearch.yml

USER elasticsearch

COPY ./elasticsearch /elasticsearch/

RUN /bin/bash bin/elasticsearch -p /tmp/epid & \
  /bin/bash /elasticsearch/scripts/wait-for-it.sh -t 0 localhost:9200 -- /elasticsearch/scripts/build-index.sh; kill $(cat /tmp/epid) && \
  wait $(cat /tmp/epid); exit 0;
```

How can the amount of steps used in the Dockerfile be related to elasticsearch service?

**Comment by rjernst** [comment]
The version this issue was based on is quite old (5.x). The official Dockerfiles to build upon can now be found in https://github.com/elastic/dockerfiles. As @xeraa mentioned, further discussion should probably be done in our [forums](https://discuss.elastic.co). There is an active community there that should be able to help.

Additionally, maintenance of the docker files for elasticsearch has moved to the elasticsearch repo. Please open any future issues with docker there. As this this repository will be archived, I am closing this issue.
