### ISSUE TITLE
Cannot remove elasticsearch plugin (x-pack) on "child" image

### ISSUE THREAD

**Issue by fabito** [elastic/elasticsearch-docker#35]
I'm trying to create a new image (extending this one) which just removes x-pack. 
Here is my Dockerfile:

```Dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2

# Uninstall xpack
RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin remove x-pack
```

When I try to build it.

```
docker build -t mynamespace/elasticsearch:5.2.2 .
```

I'm getting the following error:

```
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2
 ---> 89315294a341
Step 2/2 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin remove x-pack
 ---> Running in b17c4028966a
-> Removing x-pack...
Exception in thread "main" java.nio.file.AtomicMoveNotSupportedException: /usr/share/elasticsearch/plugins/x-pack -> /usr/share/elasticsearch/plugins/.removing-x-pack: Cross-device link
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:394)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:88)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:59)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c eval ${ES_JAVA_OPTS:-} elasticsearch-plugin remove x-pack' returned a non-zero code: 1
```

### `docker info` output

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 105
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 307
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-65-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.701 GiB
Name: cit009992
ID: JYLV:KNHK:MMQR:NSB3:3J5F:SBH3:I3K4:T7KC:JKKQ:UN5J:PEGI:3N3W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: fabito
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dliappis** [comment]
Thank you for reporting this!

This will be tackled with an Elasticsearch PR and is due to aufs/overlay allowing atomic dir renames [only on the upper layer](https://github.com/torvalds/linux/blob/v4.8-rc2/fs/overlayfs/copy_up.c#L318-L322).

In the mean time to build your customized image replace your `RUN` Dockerfile command with:

`RUN rm -rf plugins/x-pack`

Also note that you can explicitly disable x-pack with env vars as well, e.g.:

`docker run -p 9200:9200 -e 'xpack.security.enabled=false' -e 'xpack.monitoring.enabled=false' docker.elastic.co/elasticsearch/elasticsearch:5.2.2`

**Comment by jasontedor** [comment]
Thanks for bringing this issue to my attention @dliappis. I opened elastic/elasticsearch#23548.
