### ISSUE TITLE
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")

### ISSUE THREAD

**Issue by jeantil** [elastic/elasticsearch-docker#37]
* `docker info` output:
```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 39
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.933 GiB
Name: moby
ID: ELNG:I7QS:OVYM:D26P:MXM7:3UUJ:GAWR:NZWV:2DEP:T7TX:NGRE:TYWD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 45
 System Time: 2017-03-15T13:54:03.450167757Z
 EventsListeners: 3
No Proxy: *.local, 169.254/16
Username: jeantil
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* `docker-compose` version:
`docker-compose version 1.11.2, build dfed245`
* Host OS and version:
using docker4mac on mac osx sierra 10.12.3

## Bug description
I tried migrating an existing docker-compose which uses a named volume to store data. It would be sad if I had to delete the volume and recreate it 
I running the docker-compose file with the docker.elastic.co image uncommented as in  :
```
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    #image: elasticsearch:5.2.2
    environment:
      - cluster.name=rzv2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    expose:
      - "9200"
      - "9300"
    ports:
      - "9301:9300"
      - "9201:9200"
    volumes:
      - "./es:/usr/share/elasticsearch/config"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    #image: kibana:5.2.2
    links:
       - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
```
yields the following output
```
elasticsearch_1  | 2017-03-15 13:53:26,149 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch_1  | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1  | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
elasticsearch_1  | 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
elasticsearch_1  | 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
elasticsearch_1  | 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
elasticsearch_1  | 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:125)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:67)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:85)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
elasticsearch_1  |
elasticsearch_1  | 2017-03-15 13:53:26,448 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch_1  | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1  | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
elasticsearch_1  | 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:299)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
elasticsearch_1  | 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:88)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
elasticsearch_1  |
elasticsearch_1  | [2017-03-15T13:53:26,456][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/usr/share/elasticsearch/config/logging.yml], logging is configured via [/usr/share/elasticsearch/config/log4j2.properties]
elasticsearch_1  | [2017-03-15T13:53:26,694][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2017-03-15T13:53:26,721][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/rzv2]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/rzv2]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:260) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | Caused by: java.io.IOException: failed to obtain lock on /usr/share/elasticsearch/data/nodes/0
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:239) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes/0/node.lock
elasticsearch_1  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  | 	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177) ~[?:?]
elasticsearch_1  | 	at java.nio.channels.FileChannel.open(FileChannel.java:287) ~[?:1.8.0_92-internal]
elasticsearch_1  | 	at java.nio.channels.FileChannel.open(FileChannel.java:335) ~[?:1.8.0_92-internal]
elasticsearch_1  | 	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:113) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
elasticsearch_1  | 	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
elasticsearch_1  | 	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
elasticsearch_1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:226) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
elasticsearch_1  | 	... 6 more
elasticsearch_1  | 2017-03-15 13:53:26,729 pool-1-thread-1 ERROR Unable to unregister MBeans java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
elasticsearch_1  | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1  | 	at java.security.AccessController.checkPermission(AccessController.java:884)
elasticsearch_1  | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
elasticsearch_1  | 	at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:246)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:317)
elasticsearch_1  | 	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:127)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:275)
elasticsearch_1  | 	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:104)
elasticsearch_1  | 	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
elasticsearch_1  | 	at java.lang.Thread.run(Thread.java:745)
elasticsearch_1  |
docker_elasticsearch_1 exited with code 1
```

running the same docker-compose file with the previous image  uncommented works just fine.

**Comment by dliappis** [comment]
In your `docker-compose.yml` above I can't see a named volume being used for data, but instead the use of a local dir (`.es`) for your conf files. Since the image from docker.elastic.co has pre-installed x-pack what you are probably seeing here is that you are overriding the whole `/usr/share/elasticsearch/config` dir with your local dir thus also making the x-pack conf files, preinstalled with `bin/elasticsearch-plugin` in the image under `/usr/share/elasticsearch/config/x-pack`, disappear.

You have a number of options here, some of them shown below:

1. Explicitly bind mount the conf files and not the whole dir e.g.    
```yaml
volumes:
  - "<path_to_local_es_confdir>/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
```
  You can append additional customized files you may have in the volumes list e.g. `log4j2.properties` etc.

2. Disable x-pack, if you aren't using it, as explained [here](https://github.com/elastic/elasticsearch-docker/issues/35#issuecomment-285912424), in your case, via docker-compose:
```yaml
 environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
```

Btw I am not sure how your `"./es:/usr/share/elasticsearch/config"` worked exactly, as AFAIK bind mounts need to use absolute dirs for the local dir e.g. this is what I see on my Linux workstation:

```
$ docker run --rm -v './es:/usr/share/elasticsearch/config' docker.elastic.co/elasticsearch/elasticsearch:5.2.2
docker: Error response from daemon: create ./es: "./es" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path.
See 'docker run --help'.
```

I will check this again later when I get my hands on a MacOS system.

**Comment by jeantil** [comment]
>In your docker-compose.yml above I can't see a named volume being used for data, 
you are right, this was the initial configuration when I started writing the issue but then I tried a few variations and ended up pasting a docker-compose without the named volume but didn't amend the original text. Sorry about the confusion.

>Explicitly bind mount the conf files and not the whole dir e.g.
I had switched to overriding the whole dir since I update elasticsearch.yml, log4j2.properties and need to add a dozen synonym files (one for each language we work with) and in the previous image it was easier to just add the directory instead of remembering to add a mapping for  the synonym file each time we add  new language ...

I'll therefore go with option 2. 
It would be great to have a warning about these options mentioned the official documentation on the website in a "migrating from the docker hub image" section.
Maybe even have xpack disabled by default with the option to easily enable it  with these 2 options set to true to make migration from the existing "official" image easier.

>Btw I am not sure how your "./es:/usr/share/elasticsearch/config" worked exactly, 
In docker compose the bind mounts can be relative to the docker-file  https://docs.docker.com/compose/compose-file/#volumes-volumedriver this wouldn't work with a docker run.

thank you for you help on this.

**Comment by jeantil** [comment]
Additional comments:  
adding 
```
environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
```

required me to delete my containers and recreate them (`docker-compose down`) restarting the container wasn't enough and still failed to start with errors related to my data directory `/usr/share/elasticsearch/data/rzv2`  

Once I recreated the containers, I was able to start though I still get a couple exceptions right at the start but the instance seems to start anyway:
```
elasticsearch_1  | 2017-03-15 16:19:39,330 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch_1  | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1  | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
elasticsearch_1  | 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
elasticsearch_1  | 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
elasticsearch_1  | 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
elasticsearch_1  | 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:125)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:67)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:85)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
elasticsearch_1  |
elasticsearch_1  | 2017-03-15 16:19:39,665 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
elasticsearch_1  | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
elasticsearch_1  | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
elasticsearch_1  | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
elasticsearch_1  | 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
elasticsearch_1  | 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
elasticsearch_1  | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
elasticsearch_1  | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:299)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
elasticsearch_1  | 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
elasticsearch_1  | 	at org.elasticsearch.cli.Command.main(Command.java:88)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
elasticsearch_1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
elasticsearch_1  |
elasticsearch_1  | [2017-03-15T16:19:39,674][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/usr/share/elasticsearch/config/logging.yml], logging is configured via [/usr/share/elasticsearch/config/log4j2.properties]
elasticsearch_1  | [2017-03-15T16:19:39,887][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2017-03-15T16:19:39,996][INFO ][o.e.e.NodeEnvironment    ] [J-3gkgu] using [1] data paths, mounts [[/ (overlay)]], net usable_space [51.9gb], net total_space [62.7gb], spins? [possibly], types [overlay]
elasticsearch_1  | [2017-03-15T16:19:39,997][INFO ][o.e.e.NodeEnvironment    ] [J-3gkgu] heap size [491mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2017-03-15T16:19:39,999][INFO ][o.e.n.Node               ] node name [J-3gkgu] derived from node ID [J-3gkguxTlmGpnCZDxHTfg]; set [node.name] to override
elasticsearch_1  | [2017-03-15T16:19:40,001][INFO ][o.e.n.Node               ] version[5.2.2], pid[1], build[f9d9b74/2017-02-24T17:26:45.835Z], OS[Linux/4.9.12-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_92-internal/25.92-b14]
elasticsearch_1  | [2017-03-15T16:19:41,374][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2017-03-15T16:19:41,374][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [ingest-common]
elasticsearch_1  | [2017-03-15T16:19:41,375][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [lang-expression]
elasticsearch_1  | [2017-03-15T16:19:41,375][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [lang-groovy]
elasticsearch_1  | [2017-03-15T16:19:41,375][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [lang-mustache]
elasticsearch_1  | [2017-03-15T16:19:41,375][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [lang-painless]
elasticsearch_1  | [2017-03-15T16:19:41,375][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [percolator]
elasticsearch_1  | [2017-03-15T16:19:41,376][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [reindex]
elasticsearch_1  | [2017-03-15T16:19:41,376][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [transport-netty3]
elasticsearch_1  | [2017-03-15T16:19:41,376][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded module [transport-netty4]
elasticsearch_1  | [2017-03-15T16:19:41,377][INFO ][o.e.p.PluginsService     ] [J-3gkgu] loaded plugin [x-pack]
elasticsearch_1  | [2017-03-15T16:19:41,642][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
elasticsearch_1  | [2017-03-15T16:19:43,253][INFO ][o.e.n.Node               ] initialized
elasticsearch_1  | [2017-03-15T16:19:43,253][INFO ][o.e.n.Node               ] [J-3gkgu] starting ...
elasticsearch_1  | [2017-03-15T16:19:43,285][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
elasticsearch_1  | [2017-03-15T16:19:43,333][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 5f:f5:52:86:25:d5:51:3a
elasticsearch_1  | [2017-03-15T16:19:43,394][INFO ][o.e.t.TransportService   ] [J-3gkgu] publish_address {172.19.0.2:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2017-03-15T16:19:43,401][INFO ][o.e.b.BootstrapChecks    ] [J-3gkgu] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elasticsearch_1  | [2017-03-15T16:19:46,464][INFO ][o.e.c.s.ClusterService   ] [J-3gkgu] new_master {J-3gkgu}{J-3gkguxTlmGpnCZDxHTfg}{Vyr3Q9SZTF6XBWg92PL1aQ}{172.19.0.2}{172.19.0.2:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
elasticsearch_1  | [2017-03-15T16:19:46,504][INFO ][o.e.h.HttpServer         ] [J-3gkgu] publish_address {172.19.0.2:9200}, bound_addresses {[::]:9200}
elasticsearch_1  | [2017-03-15T16:19:46,505][INFO ][o.e.n.Node               ] [J-3gkgu] started
elasticsearch_1  | [2017-03-15T16:19:46,575][INFO ][o.e.g.GatewayService     ] [J-3gkgu] recovered [0] indices into cluster_state
elasticsearch_1  | [2017-03-15T16:19:47,031][INFO ][o.e.l.LicenseService     ] [J-3gkgu] license [8a52627b-815f-4087-ab46-72871257ce8d] mode [trial] - valid
elasticsearch_1  | [2017-03-15T16:19:52,934][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [buildNum]
elasticsearch_1  | [2017-03-15T16:19:52,985][INFO ][o.e.c.m.MetaDataCreateIndexService] [J-3gkgu] [.kibana] creating index, cause [api], templates [], shards [1]/[1], mappings [server, config]
```

I'll test further and come back if I encounter futher issues.

**Comment by dliappis** [comment]
>In docker compose the bind mounts can be relative to the docker-file https://docs.docker.com/compose/compose-file/#volumes-volumedriver this wouldn't work with a docker run.

Oh right, thanks for pointing this out!

**Comment by MikaelCluseau** [comment]
small reminder:
```
$ sh -c "export xpack.monitoring.enabled=false"
export: line 1: xpack.monitoring.enabled: bad variable name
```

**Comment by jarpy** [comment]
We're looking to ship an alternative system for setting environment variables that will support shell compatible declarations like `XPACK_MONITORING_ENABLED=false`. Stay tuned!

**Comment by MikaelCluseau** [comment]
Okay! :)

**Comment by jeantil** [comment]
>We're looking to ship an alternative system for setting environment variables that will support shell compatible declarations like XPACK_MONITORING_ENABLED=false. Stay tuned!
@jarpy do you have a link to an issue we can track about this? thanks :)
