### ISSUE TITLE
running es 5.2.2 in docker per documentation on elastic.co site does not work

### ISSUE THREAD

**Issue by alrooney** [elastic/elasticsearch-docker#39]
* `docker info` output:
```
alec@Alecs-MBP / $ docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 451
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 515
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: XXEV:R3TK:Q4Z7:5Z34:M625:5RH7:2K3U:3EIS:44UK:VIU3:KHRM:4DHC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-03-18T03:58:26.757918501Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
alec@Alecs-MBP / $ 
```
* `docker-compose` version:
```
alec@Alecs-MBP / $ docker-compose -v
docker-compose version 1.11.2, build dfed245
```
* Host OS and version:
OSX 10.11.6

## Bug description
documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
says to run the following: 
```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.2.2
```

This fails on my system as follows: 

```
alec@Alecs-MBP / $ docker --version
Docker version 17.03.0-ce, build 60ccb22
alec@Alecs-MBP / $ docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.2.2
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   1
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

[2017-03-18T03:57:03,945][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/linux-x86-64/libjnidispatch.so library: No space left on device
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:866) ~[jna-4.2.2.jar:4.2.2 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826) ~[jna-4.2.2.jar:4.2.2 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:140) ~[jna-4.2.2.jar:4.2.2 (b0)]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_92-internal]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_92-internal]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:104) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:203) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.2.2.jar:5.2.2]
[2017-03-18T03:57:03,957][WARN ][o.e.b.Natives            ] cannot check if running as root because JNA is not available
[2017-03-18T03:57:03,958][WARN ][o.e.b.Natives            ] cannot install system call filter because JNA is not available
[2017-03-18T03:57:03,959][WARN ][o.e.b.Natives            ] cannot register console handler because JNA is not available
[2017-03-18T03:57:03,967][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2017-03-18T03:57:03,967][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_AS beacuse JNA is not available
[2017-03-18T03:57:04,280][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.2.jar:5.2.2]
Caused by: java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:379) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:251) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:215) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:236) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
	... 6 more
Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/config/scripts: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_92-internal]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_92-internal]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_92-internal]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_92-internal]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_92-internal]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_92-internal]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_92-internal]
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:421) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:377) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:251) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:215) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:236) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
	... 6 more
alec@Alecs-MBP / $ 
```

**Comment by dliappis** [comment]
I think this may be related to the "Docker for Mac" defaults to 2GB ram.

Since you are running ES in the "dev mode" bypassing bootstrap checks, you could try limiting the memory using something like:

```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" docker.elastic.co/elasticsearch/elasticsearch:5.2.2
```

and see if that works.

If you can afford giving more ram to the linux vm that "Docker for Mac" creates, please increase the amount of RAM by following the instructions [here](https://docs.docker.com/docker-for-mac/) in the section Preferences/Memory (e.g. try 3GB).

**Comment by alrooney** [comment]
It's not the memory.  The issue is: 

```org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)```

the docker image is missing the config/scripts directory

in addition if I fix that as follows: 

```docker run --rm -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -v /tmp/esconfig/scripts:/usr/share/elasticsearch/config/scripts docker.elastic.co/elasticsearch/elasticsearch:5.2.2```

then it complains about:

```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/data/nodes: No space left on device
```

If I debug that by getting shell access to the container it seems that there is a data dir but container thinks there is no space left on the device?  Never seen that before with docker.  Is this something to do with the elasticsearch user permissions?

```
docker run -ti --rm -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -v /tmp/esconfig/scripts:/usr/share/elasticsearch/config/scripts docker.elastic.co/elasticsearch/elasticsearch:5.2.2 /bin/bash
bash-4.3$ ls -l
total 224
-rw-r--r--    1 elastics elastics     11358 Feb 24 17:24 LICENSE.txt
-rw-r--r--    1 elastics elastics    172700 Feb 24 17:24 NOTICE.txt
-rw-r--r--    1 elastics elastics      9108 Feb 24 17:24 README.textile
drwxr-xr-x    3 elastics elastics      4096 Feb 28 15:04 bin
drwxr-xr-x    4 elastics elastics      4096 Mar 20 13:30 config
drwxr-sr-x    2 elastics elastics      4096 Feb 28 14:49 data
drwxr-xr-x    2 elastics elastics      4096 Feb 28 14:49 lib
drwxr-sr-x    2 elastics elastics      4096 Feb 28 14:49 logs
drwxr-xr-x   12 elastics elastics      4096 Feb 28 14:49 modules
drwxr-xr-x    3 elastics elastics      4096 Feb 28 14:49 plugins
bash-4.3$ cd data/
bash-4.3$ ls
bash-4.3$ echo "blah" >> alec.txt
bash: echo: write error: No space left on device
bash-4.3$ df
Filesystem           1K-blocks      Used Available Use% Mounted on
none                  61893412  59529192         0 100% /
tmpfs                  1023388         0   1023388   0% /dev
tmpfs                  1023388         0   1023388   0% /sys/fs/cgroup
/dev/vda2             61893412  59529192         0 100% /etc/resolv.conf
/dev/vda2             61893412  59529192         0 100% /etc/hostname
/dev/vda2             61893412  59529192         0 100% /etc/hosts
shm                      65536         0     65536   0% /dev/shm
osxfs                244277768 163973092  80048676  67% /usr/share/elasticsearch/config/scripts
tmpfs                  1023388         0   1023388   0% /proc/kcore
tmpfs                  1023388         0   1023388   0% /proc/timer_list
tmpfs                  1023388         0   1023388   0% /proc/sched_debug
tmpfs                  1023388         0   1023388   0% /sys/firmware
```

So this works: 

```docker run --rm -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -v /tmp/esconfig/scripts:/usr/share/elasticsearch/config/scripts -v /tmp/esdata:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:5.2.2```

But strangely this does not:

```docker run --rm -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -v es_scripts:/usr/share/elasticsearch/config/scripts -v es_data:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:5.2.2```

again it fails with the "failed to create node because it can't write to the data dir" error.  So my secondary question is why do host mapped volumes work but named volumes do not.  And by the way the docker compose.yml file that uses named volumes on the elastic.co site fails to start for me too.  Really strange?  So these docker containers work for you?

**Comment by dliappis** [comment]
Sorry I skimmed through your logs too quickly and misread the lack of disk space for lack of mem.

Yes the images are working fine e.g. on [Docker for Mac 1.13.0](https://gist.github.com/mentat/cacda0a6731abfa88947cbd4d4220df4) or the latest [17.03.0-ce](https://gist.github.com/mentat/469039357a9148e05b63d6094db670bc).

As suggested by my colleague @mentat you could be running out of disk space in your MobyLinux VM (created by Docker for Mac). You could try doing some `docker rm` and `docker rmi` for stopped containers/unused images.

Also note that if you use named (or anonymous) docker volumes you don't need to bother with the permissions/ownership but if you `-v <local_dir>:/usr/share/elasticsearch/data` you need to make sure the local dir is readable/writeable by uid/gid 1000:1000.

**Comment by alrooney** [comment]
yep.  that was it.  I removed my ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 and restarted docker and that fixed the issue and I guess that explains why the anonymous volumes weren't working for me either.  Thanks.
