### ISSUE TITLE
Docker run 5.3.0 If you are trying to use ciphers with a key length greater than 128 bits on an Oracle JVM, you will need to install the unlimited strength JCE policy files.

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/elasticsearch-docker#46]
* Host OS and version: Linux Mint 18

## Bug description
```
$docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.3.0

[2017-03-29T21:00:20,116][INFO ][o.e.n.Node               ] [] initializing ...
[2017-03-29T21:00:20,182][INFO ][o.e.e.NodeEnvironment    ] [5QcqJ9x] using [1] data paths, mounts [[/ (none)]], net usable_space [193.6gb], net total_space [933.1gb], spins? [possibly], types [aufs]
[2017-03-29T21:00:20,182][INFO ][o.e.e.NodeEnvironment    ] [5QcqJ9x] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-03-29T21:00:20,183][INFO ][o.e.n.Node               ] node name [5QcqJ9x] derived from node ID [5QcqJ9xjRJKcyxaxqxv6HQ]; set [node.name] to override
[2017-03-29T21:00:20,184][INFO ][o.e.n.Node               ] version[5.3.0], pid[1], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.4.0-62-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_92-internal/25.92-b14]
**[2017-03-29T21:00:21,776][ERROR][o.e.x.s.SSLService       ] [5QcqJ9x] unsupported ciphers [[TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA]] were requested but cannot be used in this JVM, however there are supported ciphers that will be used [[TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA]]. If you are trying to use ciphers with a key length greater than 128 bits on an Oracle JVM, you will need to install the unlimited strength JCE policy files.**
[2017-03-29T21:00:21,853][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]]; nested: InvocationTargetException; nested: ElasticsearchException[failed to generate key]; nested: NoSuchAlgorithmException[HmacSHA512 KeyGenerator not available];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
```

```
$docker info
Containers: 36
 Running: 0
 Paused: 0
 Stopped: 36
Images: 328
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 314
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.3 GiB
Name: swartjie
ID: OBAE:PF6U:XIE3:IOVE:H7LT:RFXR:YJMI:2DXA:KIF5:DV4K:IOLY:I6VR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Temporary Workaround:
Dockerfile changes:**
```dockerfile
FROM **frolvlad/alpine-oraclejdk8:latest**
MAINTAINER Elastic Docker Team <docker@elastic.co>

ARG ELASTIC_VERSION
ARG ES_DOWNLOAD_URL
ARG ES_JAVA_OPTS

ENV PATH /usr/share/elasticsearch/bin:$PATH
#ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
**ENV JAVA_HOME /usr/lib/jvm/default-jvm**

WORKDIR /usr/share/elasticsearch

**RUN apk update && \
    apk upgrade && \
    apk add bash curl openssl && \
    rm -rf /var/cache/apk/***

**# Install elasticsearch user
RUN adduser -D -u 1000 -h /usr/share/elasticsearch elasticsearch**
```

[edited by @jarpy for clarity]

**Comment by dliappis** [comment]
@svanschalkwyk Can you please share the commands you use to trigger the unsupported cipher errors?

FYI for now, we are using the default (openjdk) found in the alpine:base image, as opposed to oraclejkd8 (in your example), however for 5.4.0 we are planning to move to a non musl base due to incompatibilities with forthcoming features and plugins.

**Comment by svanschalkwyk** [comment]
1. git clone the current branch
2. without changing anything, run any of the make commands
 3. $make build
`docker pull docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
latest: Pulling from elasticsearch/elasticsearch-alpine-base
Digest: sha256:7d90d00e57ddd752b2827205eb035b64cde294c7bbf671a21dc8e3f23ac00cff
Status: Image is up to date for docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
docker-compose down -v && docker-compose rm -f -v
WARNING: The ES_NODE_COUNT variable is not set. Defaulting to a blank string.
Removing elasticsearchdocker_elasticsearch1_1 ... done
Removing elasticsearchdocker_elasticsearch2_1 ... done
Removing elasticsearchdocker_tester_run_1 ... done
Removing network elasticsearchdocker_esnet
Removing volume elasticsearchdocker_esdata2
Removing volume elasticsearchdocker_esdata1
WARNING: The ES_NODE_COUNT variable is not set. Defaulting to a blank string.
No stopped containers
docker-compose build --pull elasticsearch1
WARNING: The ES_NODE_COUNT variable is not set. Defaulting to a blank string.
Building elasticsearch1
Step 1/20 : FROM docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
latest: Pulling from elasticsearch/elasticsearch-alpine-base
Digest: sha256:7d90d00e57ddd752b2827205eb035b64cde294c7bbf671a21dc8e3f23ac00cff
Status: Image is up to date for docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
 ---> 47f4aed2574c
Step 2/20 : MAINTAINER Elastic Docker Team <docker@elastic.co>
 ---> Using cache
 ---> cd84fc03fedd
Step 3/20 : ARG ELASTIC_VERSION
 ---> Using cache
 ---> d60299951f93
Step 4/20 : ARG ES_DOWNLOAD_URL
 ---> Using cache
 ---> d244f7f0e867
Step 5/20 : ARG ES_JAVA_OPTS
 ---> Using cache
 ---> b2847e518e75
Step 6/20 : ENV PATH /usr/share/elasticsearch/bin:$PATH
 ---> Using cache
 ---> d3965bcfd492
Step 7/20 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Using cache
 ---> 6e495d53fd1a
Step 8/20 : WORKDIR /usr/share/elasticsearch
 ---> Using cache
 ---> b96a865fb317
Step 9/20 : RUN wget ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz &&     EXPECTED_SHA=$(wget -O - ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz.sha1) &&     test $EXPECTED_SHA == $(sha1sum elasticsearch-${ELASTIC_VERSION}.tar.gz | awk '{print $1}') &&     tar zxf elasticsearch-${ELASTIC_VERSION}.tar.gz &&     chown -R elasticsearch:elasticsearch elasticsearch-${ELASTIC_VERSION} &&     mv elasticsearch-${ELASTIC_VERSION}/* . &&     rmdir elasticsearch-${ELASTIC_VERSION} &&     rm elasticsearch-${ELASTIC_VERSION}.tar.gz
 ---> Using cache
 ---> 2176267b30b5
Step 10/20 : RUN set -ex && for esdirs in config data logs; do         mkdir -p "$esdirs";         chown -R elasticsearch:elasticsearch "$esdirs";     done
 ---> Using cache
 ---> 033dd3286f68
Step 11/20 : USER elasticsearch
 ---> Using cache
 ---> 29cb28e2ff9c
Step 12/20 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack
 ---> Running in f309e7ad5f53
-> Downloading x-pack from elastic
Exception in thread "main" java.nio.file.AccessDeniedException: /tmp/1120278671183718126.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:852)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:271)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:318)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:227)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:206)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:192)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
ERROR: Service 'elasticsearch1' failed to build: The command '/bin/sh -c eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack' returned a non-zero code: 1
Makefile:60: recipe for target 'build' failed
make: *** [build] Error 1`

**Comment by dliappis** [comment]
Just tried the above from the master branch without issues.
To be certain that there are no cached layers or other issues, I tried the procedure on a fresh Ubuntu-16.04 vm with 2GB of ram (I used our own vagrant box: `elastic/ubuntu-16.04-x86_64` where I installed docker-engine and `pip install docker-compose`) which worked a treat[1].

One thing to note, is that for the tests to pass, you'll need to configure the `vm.max_map_count` sysctl (as they will test cluster functionality) as [explained here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode); lack of this setting though shouldn't affect the build itself in the way you've noticed.

Can you also try cleaning up your system from orphaned images/volumes etc.or execute the procedure on a different workstation/vm?

```bash
$ vagrant ssh ubuntu1604vbox
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-66-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Mar 30 15:51:04 2017 from 10.0.2.2

vagrant@ubuntu1604vbox:~$ git clone https://github.com/elastic/elasticsearch-docker.git
Cloning into 'elasticsearch-docker'...
remote: Counting objects: 461, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 461 (delta 0), reused 0 (delta 0), pack-reused 458
Receiving objects: 100% (461/461), 79.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (249/249), done.
Checking connectivity... done.

vagrant@ubuntu1604vbox:~$ sysctl vm.max_map_count
vm.max_map_count = 262144

vagrant@ubuntu1604vbox:~$ cd elasticsearch-docker/
vagrant@ubuntu1604vbox:~/elasticsearch-docker$ make
docker pull docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
latest: Pulling from elasticsearch/elasticsearch-alpine-base
3690ec4760f9: Pull complete 
f52154c3d3fc: Pull complete 
4075cc5db14a: Pull complete 
Digest: sha256:7d90d00e57ddd752b2827205eb035b64cde294c7bbf671a21dc8e3f23ac00cff
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
docker-compose down -v && docker-compose rm -f -v
Removing network elasticsearchdocker_esnet
WARNING: Network elasticsearchdocker_esnet not found.
Removing volume elasticsearchdocker_esdata2
WARNING: Volume elasticsearchdocker_esdata2 not found.
Removing volume elasticsearchdocker_esdata1
WARNING: Volume elasticsearchdocker_esdata1 not found.
No stopped containers
docker-compose up -d --build elasticsearch1
Creating network "elasticsearchdocker_esnet" with driver "bridge"
Creating volume "elasticsearchdocker_esdata2" with local driver
Creating volume "elasticsearchdocker_esdata1" with local driver
Building elasticsearch1
Step 1/20 : FROM docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
 ---> 47f4aed2574c
Step 2/20 : MAINTAINER Elastic Docker Team <docker@elastic.co>
 ---> Running in ccd1a960c78f
 ---> f5c997ce5d71
Removing intermediate container ccd1a960c78f
Step 3/20 : ARG ELASTIC_VERSION
 ---> Running in 046f48035e2e
 ---> 38174ce8ffc0
Removing intermediate container 046f48035e2e
Step 4/20 : ARG ES_DOWNLOAD_URL
 ---> Running in 8a75fbc2d97c
 ---> 2e75f327414c
Removing intermediate container 8a75fbc2d97c
Step 5/20 : ARG ES_JAVA_OPTS
 ---> Running in 31b89cd3ee2f
 ---> b7924b934770
Removing intermediate container 31b89cd3ee2f
Step 6/20 : ENV PATH /usr/share/elasticsearch/bin:$PATH
 ---> Running in 6d2bebf81ca3
 ---> 80feacf1f375
Removing intermediate container 6d2bebf81ca3
Step 7/20 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Running in 69611755f08e
 ---> 76e469576a7b
Removing intermediate container 69611755f08e
Step 8/20 : WORKDIR /usr/share/elasticsearch
 ---> 01de7cdc4f5e
Removing intermediate container aab19537dda6
Step 9/20 : RUN wget ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz &&     EXPECTED_SHA=$(wget -O - ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz.sha1) &&     test $EXPECTED_SHA == $(sha1sum elasticsearch-${ELASTIC_VERSION}.tar.gz | awk '{print $1}') &&     tar zxf elasticsearch-${ELASTIC_VERSION}.tar.gz &&     chown -R elasticsearch:elasticsearch elasticsearch-${ELASTIC_VERSION} &&     mv elasticsearch-${ELASTIC_VERSION}/* . &&     rmdir elasticsearch-${ELASTIC_VERSION} &&     rm elasticsearch-${ELASTIC_VERSION}.tar.gz
 ---> Running in 4954da9e2216
Connecting to artifacts.elastic.co (54.243.211.74:443)
elasticsearch-5.3.0. 100% |*******************************| 32907k  0:00:00 ETA
Connecting to artifacts.elastic.co (54.243.211.74:443)
-                    100% |*******************************|    40   0:00:00 ETA
 ---> 0fc4ca21073a
Removing intermediate container 4954da9e2216
Step 10/20 : RUN set -ex && for esdirs in config data logs; do         mkdir -p "$esdirs";         chown -R elasticsearch:elasticsearch "$esdirs";     done
 ---> Running in b312e3bf9f25
+ mkdir -p config
+ chown -R elasticsearch:elasticsearch config
+ mkdir -p data
+ chown -R elasticsearch:elasticsearch data
+ mkdir -p logs
+ chown -R elasticsearch:elasticsearch logs
 ---> 6607bf746666
Removing intermediate container b312e3bf9f25
Step 11/20 : USER elasticsearch
 ---> Running in 55d63d4781e9
 ---> 80de9b69a9fd
Removing intermediate container 55d63d4781e9
Step 12/20 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack
 ---> Running in 8f6de52b3418
-> Downloading x-pack from elastic
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.com.sun.activation.registries
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission setFactory
* java.security.SecurityPermission createPolicy.JavaPolicy
* java.security.SecurityPermission getPolicy
* java.security.SecurityPermission putProviderProperty.BC
* java.security.SecurityPermission setPolicy
* java.util.PropertyPermission * read,write
* java.util.PropertyPermission sun.nio.ch.bugLevel write
* javax.net.ssl.SSLPermission setHostnameVerifier
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed x-pack
 ---> f7b37ff7c1fb
Removing intermediate container 8f6de52b3418
Step 13/20 : COPY elasticsearch.yml config/
 ---> f9be3066fa55
Removing intermediate container c81aaa41ed47
Step 14/20 : COPY log4j2.properties config/
 ---> 7d7077aa5f7b
Removing intermediate container 0e48da663adc
Step 15/20 : COPY bin/es-docker bin/es-docker
 ---> 2ff7cceb3f29
Removing intermediate container 639fb07a94a8
Step 16/20 : USER root
 ---> Running in b5c0b4b86099
 ---> ae0892709a74
Removing intermediate container b5c0b4b86099
Step 17/20 : RUN chown elasticsearch:elasticsearch config/elasticsearch.yml config/log4j2.properties bin/es-docker &&     chmod 0750 bin/es-docker
 ---> Running in 100e979d4f6e
 ---> 23edcfecb133
Removing intermediate container 100e979d4f6e
Step 18/20 : USER elasticsearch
 ---> Running in cb63892e7cd2
 ---> d8c645f3e792
Removing intermediate container cb63892e7cd2
Step 19/20 : CMD /bin/bash bin/es-docker
 ---> Running in 66b8b192a171
 ---> 1ad7eecd5f5c
Removing intermediate container 66b8b192a171
Step 20/20 : EXPOSE 9200 9300
 ---> Running in e656f0985e37
 ---> e85f2f1b7c2e
Removing intermediate container e656f0985e37
Successfully built e85f2f1b7c2e
Creating elasticsearchdocker_elasticsearch1_1
docker-compose build --pull tester
Building tester
Step 1/7 : FROM alpine:latest
latest: Pulling from library/alpine
Digest: sha256:58e1a1bb75db1b5a24a462dd5e2915277ea06438c3f105138f97eb53149673c4
Status: Image is up to date for alpine:latest
 ---> 4a415e366388
Step 2/7 : RUN apk update &&     apk upgrade &&     apk add openssl python python-dev py2-pip &&     rm -rf /var/cache/apk/*
 ---> Using cache
 ---> 0543a7ac108d
Step 3/7 : RUN pip install --upgrade --quiet     requests     retrying     pytest
 ---> Using cache
 ---> c89281ee5278
Step 4/7 : RUN adduser -D -u 1000 -h /home/testuser testuser
 ---> Using cache
 ---> 9132974a237f
Step 5/7 : WORKDIR /home/testuser
 ---> Using cache
 ---> e2cbba6c770c
Step 6/7 : USER testuser
 ---> Using cache
 ---> 68645f0eb9e9
Step 7/7 : RUN mkdir /home/testuser/tests
 ---> Using cache
 ---> 7680be0b352e
Successfully built 7680be0b352e
docker-compose run tester
==================================================== test session starts =====================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/testuser, inifile:
collected 6 items 

tests/test_xpack_basic_index_crud.py ......

================================================== 6 passed in 7.75 seconds ==================================================
docker-compose down -v
Stopping elasticsearchdocker_elasticsearch1_1 ... done
Removing elasticsearchdocker_tester_run_1 ... done
Removing elasticsearchdocker_elasticsearch1_1 ... done
Removing network elasticsearchdocker_esnet
Removing volume elasticsearchdocker_esdata2
Removing volume elasticsearchdocker_esdata1
docker-compose up -d --build elasticsearch1 elasticsearch2
Creating network "elasticsearchdocker_esnet" with driver "bridge"
Creating volume "elasticsearchdocker_esdata2" with local driver
Creating volume "elasticsearchdocker_esdata1" with local driver
Building elasticsearch1
Step 1/20 : FROM docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
 ---> 47f4aed2574c
Step 2/20 : MAINTAINER Elastic Docker Team <docker@elastic.co>
 ---> Using cache
 ---> f5c997ce5d71
Step 3/20 : ARG ELASTIC_VERSION
 ---> Using cache
 ---> 38174ce8ffc0
Step 4/20 : ARG ES_DOWNLOAD_URL
 ---> Using cache
 ---> 2e75f327414c
Step 5/20 : ARG ES_JAVA_OPTS
 ---> Using cache
 ---> b7924b934770
Step 6/20 : ENV PATH /usr/share/elasticsearch/bin:$PATH
 ---> Using cache
 ---> 80feacf1f375
Step 7/20 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Using cache
 ---> 76e469576a7b
Step 8/20 : WORKDIR /usr/share/elasticsearch
 ---> Using cache
 ---> 01de7cdc4f5e
Step 9/20 : RUN wget ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz &&     EXPECTED_SHA=$(wget -O - ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz.sha1) &&     test $EXPECTED_SHA == $(sha1sum elasticsearch-${ELASTIC_VERSION}.tar.gz | awk '{print $1}') &&     tar zxf elasticsearch-${ELASTIC_VERSION}.tar.gz &&     chown -R elasticsearch:elasticsearch elasticsearch-${ELASTIC_VERSION} &&     mv elasticsearch-${ELASTIC_VERSION}/* . &&     rmdir elasticsearch-${ELASTIC_VERSION} &&     rm elasticsearch-${ELASTIC_VERSION}.tar.gz
 ---> Using cache
 ---> 0fc4ca21073a
Step 10/20 : RUN set -ex && for esdirs in config data logs; do         mkdir -p "$esdirs";         chown -R elasticsearch:elasticsearch "$esdirs";     done
 ---> Using cache
 ---> 6607bf746666
Step 11/20 : USER elasticsearch
 ---> Using cache
 ---> 80de9b69a9fd
Step 12/20 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack
 ---> Using cache
 ---> f7b37ff7c1fb
Step 13/20 : COPY elasticsearch.yml config/
 ---> Using cache
 ---> f9be3066fa55
Step 14/20 : COPY log4j2.properties config/
 ---> Using cache
 ---> 7d7077aa5f7b
Step 15/20 : COPY bin/es-docker bin/es-docker
 ---> Using cache
 ---> 2ff7cceb3f29
Step 16/20 : USER root
 ---> Using cache
 ---> ae0892709a74
Step 17/20 : RUN chown elasticsearch:elasticsearch config/elasticsearch.yml config/log4j2.properties bin/es-docker &&     chmod 0750 bin/es-docker
 ---> Using cache
 ---> 23edcfecb133
Step 18/20 : USER elasticsearch
 ---> Using cache
 ---> d8c645f3e792
Step 19/20 : CMD /bin/bash bin/es-docker
 ---> Using cache
 ---> 1ad7eecd5f5c
Step 20/20 : EXPOSE 9200 9300
 ---> Using cache
 ---> e85f2f1b7c2e
Successfully built e85f2f1b7c2e
Building elasticsearch2
Step 1/20 : FROM docker.elastic.co/elasticsearch/elasticsearch-alpine-base:latest
 ---> 47f4aed2574c
Step 2/20 : MAINTAINER Elastic Docker Team <docker@elastic.co>
 ---> Using cache
 ---> f5c997ce5d71
Step 3/20 : ARG ELASTIC_VERSION
 ---> Using cache
 ---> 38174ce8ffc0
Step 4/20 : ARG ES_DOWNLOAD_URL
 ---> Using cache
 ---> 2e75f327414c
Step 5/20 : ARG ES_JAVA_OPTS
 ---> Using cache
 ---> b7924b934770
Step 6/20 : ENV PATH /usr/share/elasticsearch/bin:$PATH
 ---> Using cache
 ---> 80feacf1f375
Step 7/20 : ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
 ---> Using cache
 ---> 76e469576a7b
Step 8/20 : WORKDIR /usr/share/elasticsearch
 ---> Using cache
 ---> 01de7cdc4f5e
Step 9/20 : RUN wget ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz &&     EXPECTED_SHA=$(wget -O - ${ES_DOWNLOAD_URL}/elasticsearch-${ELASTIC_VERSION}.tar.gz.sha1) &&     test $EXPECTED_SHA == $(sha1sum elasticsearch-${ELASTIC_VERSION}.tar.gz | awk '{print $1}') &&     tar zxf elasticsearch-${ELASTIC_VERSION}.tar.gz &&     chown -R elasticsearch:elasticsearch elasticsearch-${ELASTIC_VERSION} &&     mv elasticsearch-${ELASTIC_VERSION}/* . &&     rmdir elasticsearch-${ELASTIC_VERSION} &&     rm elasticsearch-${ELASTIC_VERSION}.tar.gz
 ---> Using cache
 ---> 0fc4ca21073a
Step 10/20 : RUN set -ex && for esdirs in config data logs; do         mkdir -p "$esdirs";         chown -R elasticsearch:elasticsearch "$esdirs";     done
 ---> Using cache
 ---> 6607bf746666
Step 11/20 : USER elasticsearch
 ---> Using cache
 ---> 80de9b69a9fd
Step 12/20 : RUN eval ${ES_JAVA_OPTS:-} elasticsearch-plugin install --batch x-pack
 ---> Using cache
 ---> f7b37ff7c1fb
Step 13/20 : COPY elasticsearch.yml config/
 ---> Using cache
 ---> f9be3066fa55
Step 14/20 : COPY log4j2.properties config/
 ---> Using cache
 ---> 7d7077aa5f7b
Step 15/20 : COPY bin/es-docker bin/es-docker
 ---> Using cache
 ---> 2ff7cceb3f29
Step 16/20 : USER root
 ---> Using cache
 ---> ae0892709a74
Step 17/20 : RUN chown elasticsearch:elasticsearch config/elasticsearch.yml config/log4j2.properties bin/es-docker &&     chmod 0750 bin/es-docker
 ---> Using cache
 ---> 23edcfecb133
Step 18/20 : USER elasticsearch
 ---> Using cache
 ---> d8c645f3e792
Step 19/20 : CMD /bin/bash bin/es-docker
 ---> Using cache
 ---> 1ad7eecd5f5c
Step 20/20 : EXPOSE 9200 9300
 ---> Using cache
 ---> e85f2f1b7c2e
Successfully built e85f2f1b7c2e
Creating elasticsearchdocker_elasticsearch2_1
Creating elasticsearchdocker_elasticsearch1_1
docker-compose build --pull tester
Building tester
Step 1/7 : FROM alpine:latest
latest: Pulling from library/alpine
Digest: sha256:58e1a1bb75db1b5a24a462dd5e2915277ea06438c3f105138f97eb53149673c4
Status: Image is up to date for alpine:latest
 ---> 4a415e366388
Step 2/7 : RUN apk update &&     apk upgrade &&     apk add openssl python python-dev py2-pip &&     rm -rf /var/cache/apk/*
 ---> Using cache
 ---> 0543a7ac108d
Step 3/7 : RUN pip install --upgrade --quiet     requests     retrying     pytest
 ---> Using cache
 ---> c89281ee5278
Step 4/7 : RUN adduser -D -u 1000 -h /home/testuser testuser
 ---> Using cache
 ---> 9132974a237f
Step 5/7 : WORKDIR /home/testuser
 ---> Using cache
 ---> e2cbba6c770c
Step 6/7 : USER testuser
 ---> Using cache
 ---> 68645f0eb9e9
Step 7/7 : RUN mkdir /home/testuser/tests
 ---> Using cache
 ---> 7680be0b352e
Successfully built 7680be0b352e
docker-compose run tester
==================================================== test session starts =====================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/testuser, inifile:
collected 6 items 

tests/test_xpack_basic_index_crud.py ......

================================================= 6 passed in 35.33 seconds ==================================================
docker-compose down -v
Stopping elasticsearchdocker_elasticsearch1_1 ... done
Stopping elasticsearchdocker_elasticsearch2_1 ... done
Removing elasticsearchdocker_tester_run_1 ... done
Removing elasticsearchdocker_elasticsearch1_1 ... done
Removing elasticsearchdocker_elasticsearch2_1 ... done
Removing network elasticsearchdocker_esnet
Removing volume elasticsearchdocker_esdata2
Removing volume elasticsearchdocker_esdata1
```

**Comment by svanschalkwyk** [comment]
You are correct: I cleaned out all images - there was one elastic-docker from 11/26/2016, which seemed to be the culprit.
So sorry to have wasted your time and resources! Mea culpa.

**Comment by dliappis** [comment]
Glad you got it sorted out!
