### ISSUE TITLE
Cannot install plugin through Dockerfile when using environment variable

### ISSUE THREAD

**Issue by pvledoux** [elastic/elasticsearch-docker#63]
## Bug Description

elasticsearch.yml:
```
cluster.name: es-cluster
node.name: es-${NODE_NAME}
network.host: 0.0.0.0
action.destructive_requires_name: true
http.cors.enabled: true
http.cors.allow-origin: "*"
```

NODE_NAME is defined in a .env file.

Dockerfile:
```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch cloud-aws
```

When starting the container, I get:
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'NODE_NAME'
	at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:116)
	at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:69)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1083)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1043)
	at org.elasticsearch.node.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:140)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:120)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:63)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

If I replace ${NODE_NAME} by a string, the container starts.

**Comment by dliappis** [comment]
@pvledoux I was able to reproduce your problem while **building** the container, as opposed to **running** (which I can't do of course because building failed). I assume you are using `docker build` to build your customized image right?

You are using the `.env` file to define `NODE_NAME`, however, this file is used only by [`docker-compose`](https://docs.docker.com/compose/env-file/), not `docker build`.

You can see what's happening yourself if you inspect the intermediate layer. I replicated your env[1] and ran `docker build -t myes .` which failed[2].

Inspecting the intermediate layer shown in [2], you can see that the `${NODE_NAME}` didn't get populated in `config/elasticsearch.yml`, therefore `elasticsearch-plugin install` correctly failed.

```yaml
$ docker run --rm -ti c0e9c6660e6a /bin/bash
bash-4.3$ cat config/elasticsearch.yml 
cluster.name: es-cluster
node.name: es-${NODE_NAME}
network.host: 0.0.0.0
action.destructive_requires_name: true
http.cors.enabled: true
http.cors.allow-origin: "*"
```

To resolve your situation, if you are trying to have your Elasticsearch `node.name` configured **during build time**, you can use the `ARG` declaration in your `Dockerfile`, together with [`--build-args`](https://docs.docker.com/engine/reference/builder/#arg) with `docker build` to pass the parameter.

[1]
```bash
$ tree
.
├── config
│   └── elasticsearch.yml
└── Dockerfile

$ cat config/elasticsearch.yml 
cluster.name: es-cluster
node.name: es-${NODE_NAME}
network.host: 0.0.0.0
action.destructive_requires_name: true
http.cors.enabled: true
http.cors.allow-origin: "*"

$ cat Dockerfile 
FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch cloud-aws
```

[2]
```bash
$ docker build -t myes .
Sending build context to Docker daemon  4.608kB
Step 1/3 : FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0
 ---> ccec59a7dd84
Step 2/3 : ADD config/elasticsearch.yml /usr/share/elasticsearch/config/
 ---> c0e9c6660e6a
Step 3/3 : RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch cloud-aws
 ---> Running in 2c2686f6e667
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'NODE_NAME'
	at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:116)
	at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:69)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1083)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1043)
	at org.elasticsearch.node.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:140)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:120)
	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:63)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch cloud-aws' returned a non-zero code: 1
```

**Comment by jarpy** [comment]
I'm not sure the intent here is to set the node name at build time. I think it's to set the node name at run time via [Elasticsearch's own variable expansion](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_environment_variable_subsitution).

If that's the case, then the order would need to be changed in the Dockerfile, so that `elasticsearch.yml` is valid when `elasticsearch-plugin` is run. You'll also want to use the correct name for the plugin, which is now `discovery-ec2`.

``` dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch discovery-ec2
ADD config/elasticsearch.yml /usr/share/elasticsearch/config/
```

Finally, the variable would need to be set at run time, with `-e` for `docker run`, or in `docker-compose.yml`. Setting it in a `.env` file will not expose the variable inside the container in either case (under docker-compose, `.env` is used to expand environment variables in `docker-compose.yml`, not to set environment variables for container processes.

```
docker run --rm -it -e NODE_NAME=mynode custom
```

``` yaml
version: '3'

services:
  elasticsearch:
    image: custom
    environment:
      - NODE_NAME=mynode
```

Having said that, there's really no need for all this. The image [already provides a mechanism to set any option you wish](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/docker.html#_a_present_the_parameters_via_docker_environment_variables). Like this:

```
docker run --rm -it -e node.name=es-mynode docker.elastic.co/elasticsearch/elasticsearch:5.4.0
```

**Comment by pvledoux** [comment]
I'm indeed using docker-compose, I'm sorry I forgot to mention it.
So I'm starting the container with `docker-compose up --build -d elasticsearch`.
I followed the recommandation of @jarpy and it resolved the issue.
Thanks a lot!
